[versions]
# https://developer.android.com/build/releases/gradle-plugin
agp = "9.0.1"

# https://developer.android.com/tools/releases/platforms
android-compileSdk = "36"
android-minSdk = "24"

# https://github.com/Kotlin/dokka/releases
dokka = "2.1.0"
# https://github.com/touchlab/Kermit/releases
kermit = "2.0.8"
# https://github.com/kotest/kotest/releases
kotest = "6.0.7"
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.2.0"
# https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-coroutines = "1.10.2"
# https://github.com/Kotlin/kotlinx-datetime/releases
kotlinx-datetime = "0.7.1"
# https://github.com/goncalossilva/kotlinx-resources/releases
kotlinx-resource = "0.14.1"
# https://github.com/Kotlin/kotlinx-kover/releases
kover = "0.9.4"
# https://github.com/google/ksp/releases
ksp = "2.3.5"
# https://github.com/ktorio/ktor/releases
ktor = "3.2.3"
# https://github.com/kingg22/ktorgen/releases
ktorgen = "0.6.0"
# https://github.com/pinterest/ktlint/releases
ktlint-pinterest = "1.7.1"
# https://github.com/jlleitschuh/ktlint-gradle/releases
ktlint-plugin = "14.0.1"
# https://github.com/vanniktech/gradle-maven-publish-plugin/releases
maven-publish = "0.36.0"
# https://github.com/drewhamilton/Poko/releases
poko = "0.19.3"

[libraries]
# Kotlin - Kotlinx essentials
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Resources multiplatform
kotlinx-resources = { group = "com.goncalossilva", name = "resources", version.ref = "kotlinx-resource" }

# Ktor
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-engine-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# ktorgen
ktorgen-annotations = { group = "io.github.kingg22", name = "ktorgen-annotations", version.ref = "ktorgen" }
ktorgen-compiler = { group = "io.github.kingg22", name = "ktorgen-compiler", version.ref = "ktorgen" }

# Logger
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

# Kotest
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json", version.ref = "kotest" }

# Libraries can be bundled together for easier import
[bundles]
kotlinx-ecosystem = [
    "kotlinx-datetime",
    # "kotlinx-serialization",
    # "kotlinx-coroutines",
]
ktor-client = [
    #"ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-json",
    "ktor-client-logging",
]
testing = [
    "kotlin-test",
    "kotlinx-coroutines-test",
    "kotest-assertions-core",
]
testing-ktor = [
    "ktor-client-mock",
    "kotlinx-resources",
    "kotest-assertions-json",
]

[plugins]
#android-library = { id = "com.android.library", version.ref = "agp" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlinx-resources = { id = "com.goncalossilva.resources", version.ref = "kotlinx-resource" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }
